Update CI

diff --git a/.github/workflows/publish-ghrch.yaml b/.github/workflows/publish-ghrch.yaml
--- a/.github/workflows/publish-ghrch.yaml
+++ b/.github/workflows/publish-ghrch.yaml
@@ -30,11 +30,21 @@ jobs:
                 python-version: ${{ matrix.python-version }}
                 architecture: 'x64'
 
-            - name: Install dependencies
+            - name: Install pipx and poetry
               run: |
                 python -m pip install pipx
                 python -m pipx ensurepath
                 python -m pipx install poetry
+
+            - name: Check for pyproject.toml
+              run: |
+               if [ ! -f pyproject.toml ]; then
+                  echo "pyproject.toml not found in $(pwd)"
+                  exit 1
+               fi
+
+            - name: Install dependencies with poetry
+              run: |
                 poetry env use python
                 poetry run pip install --upgrade pip setuptools
                 poetry install --no-root
